PL/SQL Developer Test script 3.0
257
-- Created on 28/10/2015 by ADMINISTRADOR 
declare 
  -- Local variables here
  i integer;
begin
  -- Test statements here
        insertcatalog.Country('CR','Costa Rica',2);
      insertcatalog.Country('CL','Chile',2);
      insertcatalog.Country('CN','China',4);
     insertcatalog.Country('EC','Ecuador',2);
     insertcatalog.Country('AF','Afghanistan',4);
     insertcatalog.Country('AX','Aland Islands',5);
     insertcatalog.Country('AL','Albania',5);
     insertcatalog.Country('DZ','Algeria',1);
     insertcatalog.Country('AS','American Samoa',6);
     insertcatalog.Country('AD','Andorra',5);
     insertcatalog.Country('AO','Angola',1);
     insertcatalog.Country('AI','Anguilla',2);
     insertcatalog.Country('AQ','Antarctica',3);
     insertcatalog.Country('AG','Antigua and Barbuda',2);
     insertcatalog.Country('AR','Argentina',2);
     insertcatalog.Country('AM','Armenia',4);
     insertcatalog.Country('AW','Aruba',2);
     insertcatalog.Country('AU','Australia',6);
     insertcatalog.Country('AT','Austria',5);
     insertcatalog.Country('AZ','Azerbaijan',4);
     insertcatalog.Country('BS','Bahamas',2);
     insertcatalog.Country('BH','Bahrain',4);
     insertcatalog.Country('BD','Bangladesh',4);
     insertcatalog.Country('BB','Barbados',2);
     insertcatalog.Country('BY','Belarus',5);
     insertcatalog.Country('BE','Belgium',5);
     insertcatalog.Country('BZ','Belize',2);
     insertcatalog.Country('BJ','Benin',1);
     insertcatalog.Country('BM','Bermuda',2);
     insertcatalog.Country('BT','Bhutan',4);
     insertcatalog.Country('BO','Bolivia',2);
     insertcatalog.Country('BQ','Bonaire, Sint Eustatius and Saba',2);
     insertcatalog.Country('BA','Bosnia and Herzegovina',5);
     insertcatalog.Country('BW','Botswana',1);
     insertcatalog.Country('BV','Bouvet Island',3);
     insertcatalog.Country('BR','Brazil',2);
     insertcatalog.Country('IO','British Indian Ocean Territory',4);
     insertcatalog.Country('BN','Brunei Darussalam',4);
     insertcatalog.Country('BG','Bulgaria',5);
     insertcatalog.Country('BF','Burkina Faso',1);
     insertcatalog.Country('BI','Burundi',1);
     insertcatalog.Country('KH','Cambodia',4);
     insertcatalog.Country('CM','Cameroon',1);
     insertcatalog.Country('CA','Canada',2);
     insertcatalog.Country('CV','Cape Verde',1);
     insertcatalog.Country('KY','Cayman Islands',2);
     insertcatalog.Country('CF','Central African Republic',1);
     insertcatalog.Country('TD','Chad',1);
     insertcatalog.Country('CX','Christmas Island',4);
     insertcatalog.Country('CC','Cocos (Keeling) Islands',4);
     insertcatalog.Country('CO','Colombia',2);
     insertcatalog.Country('KM','Comoros',4);
     insertcatalog.Country('CG','Congo',4);
     insertcatalog.Country('CD','Congo the Democratic Republic of the',4);
     insertcatalog.Country('CK','Cook Islands',6);
     insertcatalog.Country('CI','Côte d_Ivoire',1);
     insertcatalog.Country('HR','Croatia',5);
     insertcatalog.Country('CU','Cuba',2);
     insertcatalog.Country('CW','Curaçao',2);
     insertcatalog.Country('CY','Cyprus',5);
     insertcatalog.Country('CZ','Czech Republic',5);
     insertcatalog.Country('DK','Denmark',5);
     insertcatalog.Country('DJ','Djibouti',1);
     insertcatalog.Country('DM','Dominica',2);
     insertcatalog.Country('DO','Dominican Republic',2);
     insertcatalog.Country('EG','Egypt',1);
     insertcatalog.Country('SV','El Salvador',2);
     insertcatalog.Country('GQ','Equatorial Guinea',1);
     insertcatalog.Country('ER','Eritrea',1);
     insertcatalog.Country('EE','Estonia',5);
     insertcatalog.Country('ET','Ethiopia',1);
     insertcatalog.Country('FK','Falkland Islands (Malvinas)',2);
     insertcatalog.Country('FO','Faroe Islands',5);
     insertcatalog.Country('FJ','Fiji',6);
     insertcatalog.Country('FI','Finland',5);
     insertcatalog.Country('FR','France',5);
     insertcatalog.Country('GF','French Guiana',2);
     insertcatalog.Country('PF','French Polynesia',6);
     insertcatalog.Country('TF','French Southern Territories',6);
     insertcatalog.Country('GA','Gabon',1);
     insertcatalog.Country('GM','Gambia',1);
     insertcatalog.Country('GE','Georgia',5);
     insertcatalog.Country('DE','Germany',5);
     insertcatalog.Country('GH','Ghana',1);
     insertcatalog.Country('GI','Gibraltar',5);
     insertcatalog.Country('GR','Greece',5);
     insertcatalog.Country('GL','Greenland',5);
     insertcatalog.Country('GD','Grenada',2);
     insertcatalog.Country('GP','Guadeloupe',2);
     insertcatalog.Country('GU','Guam',6);
     insertcatalog.Country('GT','Guatemala',2);
     insertcatalog.Country('GG','Guernsey',5);
     insertcatalog.Country('GN','Guinea',1);
     insertcatalog.Country('GW','Guinea-Bissau',1);
     insertcatalog.Country('GY','Guyana',2);
     insertcatalog.Country('HT','Haiti',2);
     insertcatalog.Country('HM','Heard Island_and McDonald Islands',6);
     insertcatalog.Country('VA','Holy See (Vatican City State)',5);
     insertcatalog.Country('HN','Honduras',2);
     insertcatalog.Country('HK','Hong Kong',4);
     insertcatalog.Country('HU','Hungary',5);
     insertcatalog.Country('IS','Iceland',5);
     insertcatalog.Country('IN','India',4);
     insertcatalog.Country('ID','Indonesia',4);
     insertcatalog.Country('IR','Iran Islamic Republic ',4);
     insertcatalog.Country('IQ','Iraq',4);
     insertcatalog.Country('IE','Ireland',5);
     insertcatalog.Country('IM','Isle Man',5);
     insertcatalog.Country('IL','Israel',4);
     insertcatalog.Country('IT','Italy',5);
     insertcatalog.Country('JM','Jamaica',2);
     insertcatalog.Country('JP','Japan',4);
     insertcatalog.Country('JE','Jersey',5);
     insertcatalog.Country('JO','Jordan',4);
     insertcatalog.Country('KZ','Kazakhstan',4);
     insertcatalog.Country('KE','Kenya',1);
     insertcatalog.Country('KI','Kiribati',6);
     insertcatalog.Country('KP','Korea Democratic Peoples Republic',4);
     insertcatalog.Country('KR','Korea Republic',4);
     insertcatalog.Country('KW','Kuwait',4);
     insertcatalog.Country('KG','Kyrgyzstan',4);
     insertcatalog.Country('LA','Lao Peoples Democratic Republic',4);
     insertcatalog.Country('LV','Latvia',5);
     insertcatalog.Country('LB','Lebanon',4);
     insertcatalog.Country('LS','Lesotho',1);
     insertcatalog.Country('LR','Liberia',1);
     insertcatalog.Country('LY','Libya',1);
     insertcatalog.Country('LI','Liechtenstein',5);
     insertcatalog.Country('LT','Lithuania',5);
     insertcatalog.Country('LU','Luxembourg',5);
     insertcatalog.Country('MO','Macao',4);
     insertcatalog.Country('MK','Macedonia former Yugoslav Republic',5);
     insertcatalog.Country('MG','Madagascar',1);
     insertcatalog.Country('MW','Malawi',1);
     insertcatalog.Country('MY','Malaysia',4);
     insertcatalog.Country('MV','Maldives',4);
     insertcatalog.Country('ML','Mali',1);
     insertcatalog.Country('MT','Malta',5);
     insertcatalog.Country('MH','Marshall Islands',6);
     insertcatalog.Country('MQ','Martinique',2);
     insertcatalog.Country('MR','Mauritania',1);
     insertcatalog.Country('MU','Mauritius',1);
     insertcatalog.Country('YT','Mayotte',1);
     insertcatalog.Country('MX','Mexico',2);
     insertcatalog.Country('FM','Micronesia Federated States',6);
     insertcatalog.Country('MD','Moldova Republic',5);
     insertcatalog.Country('MC','Monaco',5);
     insertcatalog.Country('MN','Mongolia',4);
     insertcatalog.Country('ME','Montenegro',5);
     insertcatalog.Country('MS','Montserrat',2);
     insertcatalog.Country('MA','Morocco',1);
     insertcatalog.Country('MZ','Mozambique',1);
     insertcatalog.Country('MM','Myanmar',4);
     insertcatalog.Country('NA','Namibia',1);
     insertcatalog.Country('NR','Nauru',6);
     insertcatalog.Country('NP','Nepal',4);
     insertcatalog.Country('NL','Netherlands',5);
     insertcatalog.Country('NC','New_Caledonia',6);
     insertcatalog.Country('NZ','New_Zealand',5);
     insertcatalog.Country('NI','Nicaragua',2);
     insertcatalog.Country('NE','Niger',1);
     insertcatalog.Country('NG','Nigeria',1);
     insertcatalog.Country('NU','Niue',6);
     insertcatalog.Country('NF','Norfolk Island',6);
     insertcatalog.Country('MP','Northern Mariana Islands',6);
     insertcatalog.Country('NO','Norway',5);
     insertcatalog.Country('OM','Oman',4);
     insertcatalog.Country('PK','Pakistan',4);
     insertcatalog.Country('PW','Palau',6);
     insertcatalog.Country('PS','Palestinian Territory, Occupied',4);
     insertcatalog.Country('PA','Panama',2);
     insertcatalog.Country('PG','Papua Nueva Guinea',6);
     insertcatalog.Country('PY','Paraguay',2);
     insertcatalog.Country('PE','Peru',2);
     insertcatalog.Country('PH','Philippines',4);
     insertcatalog.Country('PN','Pitcairn',6);
     insertcatalog.Country('PL','Poland',5);
     insertcatalog.Country('PT','Portugal',5);
     insertcatalog.Country('PR','Puerto Rico',2);
     insertcatalog.Country('QA','Qatar',4);
     insertcatalog.Country('RE','Réunion',1);
     insertcatalog.Country('RO','Romania',5);
     insertcatalog.Country('RU','Russian Federation',5);
     insertcatalog.Country('RW','Rwanda',1);
     insertcatalog.Country('BL','Saint Barthélemy',2);
     insertcatalog.Country('SH','Saint Helena, Ascension_and Tristan da Cunha',1);
     insertcatalog.Country('KN','Saint Kitts_and Nevis',2);
     insertcatalog.Country('LC','Saint Lucia',2);
     insertcatalog.Country('MF','Saint Martin (French part)',2);
     insertcatalog.Country('PM','Saint Pierre_and Miquelon',2);
     insertcatalog.Country('VC','Saint Vincent_and_the Grenadines',5);
     insertcatalog.Country('WS','Samoa',6);
     insertcatalog.Country('SM','San Marino',5);
     insertcatalog.Country('ST','Sao Tome_and Principe',1);
     insertcatalog.Country('SA','Saudi Arabia',4);
     insertcatalog.Country('SN','Senegal',1);
     insertcatalog.Country('RS','Serbia',5);
     insertcatalog.Country('SC','Seychelles',1);
     insertcatalog.Country('SL','Sierra Leone',1);
     insertcatalog.Country('SG','Singapore',4);
     insertcatalog.Country('SX','Sint Maarten (Dutch part)',2);
     insertcatalog.Country('SK','Slovakia',5);
     insertcatalog.Country('SI','Slovenia',5);
     insertcatalog.Country('SB','Solomon Islands',6);
     insertcatalog.Country('SO','Somalia',1);
     insertcatalog.Country('ZA','South Africa',1);
     insertcatalog.Country('GS','South Georgia_and the_South Sandwich Islands',2);
     insertcatalog.Country('SS','South Sudan',1);
     insertcatalog.Country('ES','Spain',5);
     insertcatalog.Country('LK','Sri Lanka',4);
     insertcatalog.Country('SD','Sudan',1);
     insertcatalog.Country('SR','Suriname',2);
     insertcatalog.Country('SJ','Svalbard_and Jan Mayen',5);
     insertcatalog.Country('SZ','Swaziland',1);
     insertcatalog.Country('SE','Sweden',5);
     insertcatalog.Country('CH','Switzerland',5);
     insertcatalog.Country('SY','Syrian Arab Republic',4);
     insertcatalog.Country('TW','Taiwan, Province_of China',4);
     insertcatalog.Country('TJ','Tajikistan',4);
     insertcatalog.Country('TZ','Tanzania, United Republic_of',1);
     insertcatalog.Country('TH','Thailand',4);
     insertcatalog.Country('TL','Timor-Leste',4);
     insertcatalog.Country('TG','Togo',1);
     insertcatalog.Country('TK','Tokelau',6);
     insertcatalog.Country('TO','Tonga',6);
     insertcatalog.Country('TT','Trinidad_and Tobago',2);
     insertcatalog.Country('TN','Tunisia',1);
     insertcatalog.Country('TR','Turkey',4);
     insertcatalog.Country('TM','Turkmenistan',4);
     insertcatalog.Country('TC','Turks_and Caicos Islands',2);
     insertcatalog.Country('TV','Tuvalu',6);
     insertcatalog.Country('UG','Uganda',1);
     insertcatalog.Country('UA','Ukraine',5);
     insertcatalog.Country('AE','United Arab Emirates',4);
     insertcatalog.Country('GB','United Kingdom',5);
     insertcatalog.Country('US','United States',2);
     insertcatalog.Country('UM','United States Minor Outlying Islands',2);
     insertcatalog.Country('UY','Uruguay',2);
     insertcatalog.Country('UZ','Uzbekistan',4);
     insertcatalog.Country('VU','Vanuatu',6);
     insertcatalog.Country('VE','Venezuela Bolivarian Republic_of',2);
     insertcatalog.Country('VN','Viet Nam',4);
     insertcatalog.Country('VG','Virgin Islands, British',2);
     insertcatalog.Country('VI','Virgin Islands, U.S.',2);
     insertcatalog.Country('WF','Wallis_and Futuna',6);
     insertcatalog.Country('EH','Western Sahara',1);
     insertcatalog.Country('YE','Yemen',4);
     insertcatalog.Country('ZM','Zambia',1);
     insertcatalog.Country('ZW','Zimbabwe',1);

end;
0
0
